# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

---
# ---------------------------------#
#       general configuration      #
# ---------------------------------#

# version format
version: 0.{build}

# branches to build
branches:
  # whitelist
  only:
    - add_windows_support

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

# ---------------------------------#
#    environment configuration    #
# ---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# clone directory
clone_folder: c:\projects\hdlcc

# fetch repository as zip archive
shallow_clone: false

# set clone depth
clone_depth: 5

# environment variables
environment:
  CACHE_PATH: "%LOCALAPPDATA%\\cache"
  matrix:
    - BUILDER_NAME: ghdl
      INSTALL_DIR: "%LOCALAPPDATA%\\ghdl-0.31-mcode-win32"
      arch: 32
      URL: http://pilotfiber.dl.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.31/Windows/ghdl-0.31-mcode-win32.zip
      # URL: http://pilotfiber.dl.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.33/ghdl-0.33-win32.zip"
    - BUILDER_NAME: ghdl
      INSTALL_DIR: "%LOCALAPPDATA%\\ghdl-0.31-mcode-win32"
      arch: 64
      URL: http://pilotfiber.dl.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.31/Windows/ghdl-0.31-mcode-win32.zip
      # URL: http://pilotfiber.dl.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.33/ghdl-0.33-win32.zip"
    - BUILDER_NAME: msim
      BUILDER_PATH: "%LOCALAPPDATA%\\modelsim_ase\\win32aloem"
      arch: 32
      URL: http://download.altera.com/akdlm/software/acdsinst/15.1/185/ib_installers/ModelSimSetup-15.1.0.185-windows.exe
      MODELTECH: '%LOCALAPPDATA%\modelsim_ase\win32aloem'
      MSIM_VER: 10.4b
    - BUILDER_NAME: msim
      BUILDER_PATH: "%LOCALAPPDATA%\\modelsim_ase\\win32aloem"
      arch: 64
      URL: http://download.altera.com/akdlm/software/acdsinst/15.1/185/ib_installers/ModelSimSetup-15.1.0.185-windows.exe
      MODELTECH: '%LOCALAPPDATA%\modelsim_ase\win32aloem'
      MSIM_VER: 10.4b


# build cache to preserve files/folders between builds
# cache:
#   - '%CACHE_PATH%'

# scripts that run after cloning repository
install:
  - appveyor AddMessage "Starting path is %CD%" -Category Information
  - git submodule update --init --recursive
  - ps: $env:python = if ($env:arch -eq 32) { 'C:\Python27' } else
                                            { 'C:\Python27-x64' }

  - appveyor AddMessage "Python selected is %python%"
  # - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - set PATH=%python%;%python%\Scripts;%PATH%
  # - python get-pip.py
  - pip install -r requirements.txt
  - if not exist "%CACHE_PATH%" mkdir "%CACHE_PATH%"
  - appveyor AddMessage "Configured builder is %BUILDER_NAME%"

  - if "%BUILDER_NAME%" == "msim"
      call %APPVEYOR_BUILD_FOLDER%\\scripts\\setup_msim.bat

  - if "%BUILDER_NAME%" == "ghdl"
      call %APPVEYOR_BUILD_FOLDER%\\scripts\\setup_ghdl.bat

  - if "%BUILDER_NAME%" == "msim"
      %BUILDER_PATH%\\vcom -version

  - "python %APPVEYOR_BUILD_FOLDER%\\run_tests.py -vv -F -B --log-capture"

# We won't build or run tests from here
build: off
test: off
