engines:
  duplication:
    enabled: true
    exclude_fingerprints:
      - 0655784473047c89aa4f852195dfebd1 # Duplication on hdlcc.exceptions
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config: 
      python_version: 2
      threshold: "C"
ratings:
  paths:
    - "**.py"
exclude_paths:
  - hdlcc/tests/*

