language: python
python:
  - "2.7"

before_script:
    - "git submodule update"
    - "mkdir -p ~/ghdl"
    - "cd ~/ghdl"
    - "if [ ! -f ghdl.tar.gz ]; then wget http://downloads.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.33/ghdl-0.33-x86_64-linux.tgz -O ghdl.tar.gz; fi"
    - "if [ ! -f modelsim.run ]; then wget http://download.altera.com/akdlm/software/acdsinst/15.1/185/ib_installers/ModelSimSetup-15.1.0.185-linux.run -O modelsim.run; fi"
    - "tar zxvf ghdl.tar.gz"
    - "cd -"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - "./run_tests.py -vv --log-capture --clear"
after_failure:
  - "cat tests.log"
after_success:
  - "rm -f dependencies/hdl_lib/osvvm_lib/CoveragePkg.vhd"
  - "coverage combine"
  - "codecov"
cache:
  directories:
  - ~/ghdl/

